BEGIN TRANSACTION;
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (1, 'Anonimo', 'Anonimo', 'Sconosciuta');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (2, 'Agatha', 'Christie', 'Britannica');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (3, 'Albert', 'Camus', 'Francese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (4, 'Aldous', 'Huxley', 'Britannico');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (5, 'Bret Easton', 'Ellis', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (6, 'Charles', 'Portis', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (7, 'Conan', 'Doyle', 'Scozzese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (8, 'Cormac', 'McCarthy', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (9, 'Elfriede', 'Jelinek', 'Austriaca');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (10, 'Emil M.', 'Cioran', 'Rumeno');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (11, 'Epitteto', '', 'Greco');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (12, 'Fernando', 'Pessoa', 'Portoghese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (13, 'Franz', 'Kafka', 'Boemo');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (14, 'Fëdor', 'Dostoevskij', 'Russo');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (15, 'Gabriel', 'Garcìa Marquez', 'Colombiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (16, 'Giovanni', 'Filoramo', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (17, 'Giuseppe', 'Cambiano', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (18, 'Hannah', 'Arendt', 'Tedesco');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (19, 'Howard Philips', 'Lovecraft', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (20, 'Jean Louis', 'Ska', 'Belga');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (21, 'Jean Paul', 'Sartre', 'Francese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (22, 'Luca', 'Fonnesu', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (23, 'Lucio Anneo', 'Seneca', 'Latino');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (24, 'Marcello', 'Massenzio', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (25, 'Marco', 'Aurelio', 'Romano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (26, 'Marco Tullio', 'Cicerone', 'Romano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (27, 'Marshall', 'McLuhan', 'Canadese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (28, 'Massimo', 'Mori', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (29, 'Massimo', 'Raveri', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (30, 'Neil', 'Postman', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (31, 'Paolo', 'Scarpi', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (32, 'Pier Paolo', 'Pasolini', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (33, 'Pierre', 'Boulle', 'Francese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (34, 'Ray', 'Bradbury', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (35, 'Riccardo', 'Calimani', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (36, 'Riccardo', 'Di Segni', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (37, 'Richard', 'Matheson', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (38, 'Salvatore', 'Spera', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (39, 'Søren', 'Kierkegaard', 'Danese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (40, 'Valeria', 'Arnaldi', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (41, 'Viktor Emil', 'Frankl', 'Austriaco');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (42, 'Walter', 'Tevis', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (43, 'Franz', 'Kafka', 'Boemo');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (44, 'Gaston', 'Leroux', 'Francese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (45, 'Platone', ' ', 'Greco');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (46, 'Arcangelo', 'Mazzoleni', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (47, 'Giovanni', 'Reale', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (48, 'Marie-Henri', 'Beyle', 'Francese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (49, 'Marco', 'Travaglio', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (50, 'Umberto', 'Eco', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (51, 'Lewis', 'Carroll', 'Britannico');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (52, 'Robert Louis', 'Stevenson', 'Scozzese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (53, 'Byung-chul', 'Han', 'Sudcoreano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (54, 'Herman', 'Melville', 'Statunitense');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (55, 'Pier Vittorio', 'Tondelli', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (56, 'Bernard', 'Mandeville', 'Olandese');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (57, 'Guia', 'Soncini', 'Italiano');
INSERT INTO Autori (IDAutore, NomeAutore, CognomeAutore, NazionalitàAutore) VALUES (58, 'Günter', 'Grass', 'Tedesco');
COMMIT TRANSACTION;