BEGIN TRANSACTION
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (1, 'Antonio', 'Tabucchi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (2, 'Claudio', 'De Nardi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (3, 'Lauro', 'Colasanti');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (4, 'Remo', 'Cantoni');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (5, 'Carlo', 'Laurenti');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (6, 'Gianna', 'Lonza');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (7, 'Giuseppe', 'Lippi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (8, 'K.M.', 'Guldbrandsen');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (9, 'Maria Josè', 'De Lancastre');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (10, 'Stefano', 'Galli');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (11, 'Alfredo', 'Polledro');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (12, 'Angelo', 'Morino');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (13, 'Attilio', 'Borelli');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (14, 'Bruno', 'Fonzi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (15, 'Carlo', 'Saggio');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (16, 'Cesare', 'Cassanmagnago');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (17, 'Ettore', 'Capriolo');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (18, 'Eugenio', 'Fizzotti');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (19, 'Franco', 'Fortini');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (20, 'Giacinta', 'De Dominicis Jorio');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (21, 'Giovanna', 'Scocchera');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (22, 'Giovanni', 'Reale');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (23, 'Giulio', 'Schiavoni');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (24, 'Giuseppe', 'Lippi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (25, 'Leone', 'Diena');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (26, 'Liliana', 'Magrini');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (27, 'Lorenzo', 'Flabbi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (28, 'Lorenzo', 'Gigli');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (29, 'Luciano', 'Tibiletti');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (30, 'Marco', 'Rossari');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (31, 'Maria', 'Buitoni Duca');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (32, 'Marisa', 'Caramella');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (33, 'Martina', 'Testa');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (34, 'Piero', 'Bernardini');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (35, 'Rossana', 'Sarchielli');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (36, 'Sergio Claudio', 'Perroni');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (37, 'Tullio', 'Dobner');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (38, 'Yasmina', 'Melaouah');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (39, 'Conferenza Episcopale', 'Italiana');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (40, 'Ervino', 'Pocar');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (41, 'Serena', 'Prina');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (42, 'Anita', 'Rho');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (43, 'Renzo', 'Rossi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (44, 'Giuseppe', 'Culicchia');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (45, 'Ezio', 'Savino');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (46, 'Cinzia', 'Bigliosi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (47, 'Luigi', 'Lunari');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (48, 'Barbara', 'Lanati');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (49, 'Vittorio', 'Tamaro');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (50, 'SimoneAglan', 'Buttazzi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (51, 'Federica', 'Buongiorno');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (52, 'Gianni', 'Celati');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (53, 'Tito', 'Magri');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (54, 'Bruna', 'Bianchi');
INSERT INTO Traduttori (IDTraduttore, NomeTraduttore, CognomeTraduttore) VALUES (55, 'Non Tradotto', 'Non Tradotto');
COMMIT TRANSACTION